### PR TITLE
Add firebase-admin and nodemailer dependencies and create front end f…

### PR DESCRIPTION
**Pull request by NatanAmado**
…or contact form

We still need to implement the backend logic to:

- Store each form submission in Firestore.
- Trigger a Cloud Function when a new submission is added.
- Send an email with the submission details using something like nodemailer

### CODE REVIEW

**Comment by ovirandunu** [comment]
This is too complex and needs more work. Which is why I said use something like typeform with is serverless, already hosted for us and easily integratable. So please switch to a non self hosted alternative.

**Comment by NatanAmado** [comment]
@ovirandunu there's no free alternative to typeform that isn't self-hosted

**Comment by ovirandunu** [comment]
here is an alternative:

https://www.fillout.com/help/embed-forms-react


can integrate with react. 1000 responses per month on free tier which includes some frontend customizability also

**Comment by NatanAmado** [comment]
Replaced contact form with a fillout form

**Pull request merged**
