### PR TITLE
148 style go pro modals

### PR DESCRIPTION
**Pull request by NatanAmado**

### CODE REVIEW

**Comment by noahlabear** [comment]
Great now make sure the go pro model is implemented  for when you run out of credits for every ai tool we have on the website.

If I have to remind or you return this to me without implementing it to every one of our ai tools, you will be promptly executed.

Bless.

**Comment by NatanAmado** [comment]
But it does brother

**Comment by NatanAmado** [comment]
@noahlabear

**Comment by noahlabear** [comment]
> But it does brother

but it doesn't brother

**Comment by NatanAmado** [comment]
Could you please describe in what situations this component doesn't show? I'll also update the bug that's in the sidebar when trying to sync

**Comment by noahlabear** [comment]
> Great now make sure the go pro model is implemented for when you run out of credits for every ai tool we have on the website.
> 
> If I have to remind or you return this to me without implementing it to every one of our ai tools, you will be promptly executed.
> 
> Bless.

When you are out of credits as a free or pro user. There is supposed to be a go pro modal with specific text relating to running out of credits according to the users tier. If free then say you can upgrade to pro and otherwise it will reset at 0:00 -2GMT (make sure this is the format). If pro just say you will get 1000 at specified time. You can look in to the previous commits or older branches (for example socket-fix just to get reference for how its supposed to work, change ur credits to 0 in firebase online console in the firestore database.) Let me know if you need any more clarification. @NatanAmado

**Comment by NatanAmado** [comment]
@noahlabear This pull request is ready

**Pull request merged**
