### PR TITLE
refactor: Add shadcn-ui package and Alert component

### PR DESCRIPTION
**Pull request by NatanAmado**
- Added the shadcn-ui package to the project dependencies.
- Created a new Alert component in the src/components/ui directory.
- Improved feedback to user  when adding or deleting collaborators

### CODE REVIEW

**Comment by noahlabear** [comment]
For me when added and changes saved, email shows momentarily then disappears, might just be my computer since it loads after I inspect element but yeah.

**Comment by NatanAmado** [comment]
Weird. I'll look into that

**Comment by ovirandunu** [comment]
im gonna update the branch with main

**Comment by ovirandunu** [comment]
Any update on this @NatanAmado

**Comment by NatanAmado** [comment]
> Any update on this @NatanAmado

Working on it now

**Comment by ovirandunu** [comment]
Epic

**Comment by NatanAmado** [comment]
On my computer, it seems to work fine. However, I changed the rendering logic a bit. Try it out and let me know.

**Comment by ovirandunu** [comment]
Bro can u try different browsers

**Comment by ovirandunu** [comment]
Yeah test on different browsers and then merge main into your branch and try running a build

**Comment by NatanAmado** [comment]
It now works on all my browsers

**Comment by ovirandunu** [comment]
Okok, so before the last commit it didn't?

**Comment by noahlabear** [comment]
Problem still persists, try storing it as an array of collaborators and *update it onsnapshot* to the collaborators list in workspace collection. Or some other method as you please.

**Pull request closed without merging**
